<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Najwa Laila cv</title>';
echo '<link rel="stylesheet" href="file.css">';
echo '</head>';
echo '<body>';
echo '<div class="container">';
echo '<div class="box2">';
echo '<h2 class="education">EDUCATION</h2>';
echo '<p class="ebox">Bachelor in Informatic, Universitas Pembangunan Nasional “Veteran” Jawa Timur<br>';
echo 'High School Diploma - SMA NEGERI 2 NGANJUK (2018 - 2021)<br>';
echo 'Middle School Diploma - SMP NEGERI 1 PRAMBON (2015 – 2018)<br>';
echo '</p>';
echo '<h2 class="skill">PERSONAL SKILLS</h2>';
echo '<p class="sbox">Communicative<br>';
echo 'Teamwork<br>';
echo '</p>';
echo '<div class="box4">';
echo '<h2 class="contact">CONTACT</h2>';
echo '<p class="cbox">';
echo '<a style="color:white" href="https://wa.me/+6285715743327" target="_blank">wa.me/6285715743327</a>';
echo '<br><a style="color: white;" href="https://www.instagram.com/najwwalailaa/" target="_blank">instagram.com/najwwalailaa</a></br>';
echo '<a style="color: white;" href="https://github.com/najwalailaa" target="_blank">github.com/najwalailaa</a>';
echo '<br><a style="color: white;" href="https://bit.ly/mapsnganjuk" target="_blank">Nganjuk, East  Java</a></br>';
echo '</p>';
echo '</div>';
echo '</div>';
echo '<div class="boxbesar">';
echo '<div class="font4">02</div>';
echo '<div class="font5">NAJWA LAILA ANGGRAINI</div>';
echo '<div class="org">ORGANIZATION EXPERIENCES</div>';
echo '<div class="orgisi">';
echo '<h2 class="orgbox1">(SECRETARY of DEPARTMENT PENDIDIKAN HIMATIFA 2022/2023), (HIMATIFA UPN JATIM)</h2>';
echo '<td><li class="orgbox2" >Organizing files and letter. <li class="orgbox2">Preparing documents <li class="orgbox2">Supports the management and administration with tasks and clerial duties to increas the effeciency of the department workflow. <li class="orgbox2">Help in providing information to staff department.<li class="orgbox2" >Schedulling appointments. <li class="orgbox2">Help edit, copy, transcribe, format, retrieve and transmit data, text, and graphics.</td>';
echo '<h2 class="orgbox1">(TREASURER), (HIMATIFA DESIGN CONTEST)</h2>';
echo '<td><li class="orgbox2" >Financial planning and budgeting. <li class="orgbox2"> Financial reporting </td>';
echo '<h2 class="orgbox1">(SECRETARY), (IT CAMP x FOWTEDU 2023)</h2>';
echo '<td><li class="orgbox2" >Organizing files and letter. <li class="orgbox2">Preparing documents. <li class="orgbox2">Lead the meet. <li class="orgbox2">Schedulling appointments.<li class="orgbox2" >Invite partnership.</td>';
echo '<h2 class="orgbox1">(SECRETARY), (KULIAH TAMU HIMATIFA 2022)</h2>';
echo '<td><li class="orgbox2" >Organizing files and letter. <li class="orgbox2">Preparing documents. <li class="orgbox2">Lead the meet. <li class="orgbox2">Schedulling appointments.<li class="orgbox2" >Invite partnership.</td>';
echo '<h2 class="orgbox1">(STAFF PERKAP), (PORSIMNAS UPN 2022)</h2>';
echo '<td><li class="orgbox2" >Prepare all the necessary equipment. <li class="orgbox2"> A price survey with multiple stores.</td>';
echo '<h2 class="orgbox1">(PART OF BRAND AMBASSADOR MAJU INDONESIA)</h2>';
echo '<td><li class="orgbox2" > Make informative videos.</td>';
echo '</div>';
echo '<a style="margin-left: 280px;" href="page1.php"><button>home</button></a>';
echo '</div>';
echo '</div>';
echo '</body>';
echo '</html>';
echo '';
?>